//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BancoDadosZe.Properties {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BancoDadosZe.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _3646694 {
            get {
                object obj = ResourceManager.GetObject("3646694", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap adicionar_42 {
            get {
                object obj = ResourceManager.GetObject("adicionar_42", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &amp;Adicionar.
        /// </summary>
        internal static string btn_adicionar {
            get {
                return ResourceManager.GetString("btn_adicionar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &amp;Buscar.
        /// </summary>
        internal static string btn_busca {
            get {
                return ResourceManager.GetString("btn_busca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &amp;Editar.
        /// </summary>
        internal static string btn_editar {
            get {
                return ResourceManager.GetString("btn_editar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Importar XML.
        /// </summary>
        internal static string btn_importar {
            get {
                return ResourceManager.GetString("btn_importar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Remover.
        /// </summary>
        internal static string btn_remover {
            get {
                return ResourceManager.GetString("btn_remover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Salvar.
        /// </summary>
        internal static string btn_salvar {
            get {
                return ResourceManager.GetString("btn_salvar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Escolha.
        /// </summary>
        internal static string campo_escolha {
            get {
                return ResourceManager.GetString("campo_escolha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap diagram_49_24468 {
            get {
                object obj = ResourceManager.GetObject("diagram-49_24468", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap editar {
            get {
                object obj = ResourceManager.GetObject("editar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap enter_42 {
            get {
                object obj = ResourceManager.GetObject("enter_42", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap enter_68 {
            get {
                object obj = ResourceManager.GetObject("enter_68", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap enter_icon_icons_com_71207 {
            get {
                object obj = ResourceManager.GetObject("enter_icon-icons.com_71207", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_42 {
            get {
                object obj = ResourceManager.GetObject("file_42", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fornecedor {
            get {
                object obj = ResourceManager.GetObject("fornecedor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fornecedor_80 {
            get {
                object obj = ResourceManager.GetObject("fornecedor_80", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fornecedor1 {
            get {
                object obj = ResourceManager.GetObject("fornecedor1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap funcionarios {
            get {
                object obj = ResourceManager.GetObject("funcionarios", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap imagemApp {
            get {
                object obj = ResourceManager.GetObject("imagemApp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap produto_80 {
            get {
                object obj = ResourceManager.GetObject("produto_80", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap produto_801 {
            get {
                object obj = ResourceManager.GetObject("produto_801", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ativo.
        /// </summary>
        internal static string radio_ativo {
            get {
                return ResourceManager.GetString("radio_ativo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Feminino.
        /// </summary>
        internal static string radio_feminino {
            get {
                return ResourceManager.GetString("radio_feminino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Filial.
        /// </summary>
        internal static string radio_filial {
            get {
                return ResourceManager.GetString("radio_filial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Inativo.
        /// </summary>
        internal static string radio_inativo {
            get {
                return ResourceManager.GetString("radio_inativo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Masculino.
        /// </summary>
        internal static string radio_masculino {
            get {
                return ResourceManager.GetString("radio_masculino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Matriz.
        /// </summary>
        internal static string radio_matriz {
            get {
                return ResourceManager.GetString("radio_matriz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap settings_42 {
            get {
                object obj = ResourceManager.GetObject("settings_42", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap store_78 {
            get {
                object obj = ResourceManager.GetObject("store_78", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap store_icon_icons_com_54371 {
            get {
                object obj = ResourceManager.GetObject("store_icon-icons.com_54371", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Abrir.
        /// </summary>
        internal static string titulo_abrir {
            get {
                return ResourceManager.GetString("titulo_abrir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A&amp;justes.
        /// </summary>
        internal static string titulo_ajustes {
            get {
                return ResourceManager.GetString("titulo_ajustes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Área de Atuação.
        /// </summary>
        internal static string titulo_atuacao {
            get {
                return ResourceManager.GetString("titulo_atuacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Bairro.
        /// </summary>
        internal static string titulo_bairro {
            get {
                return ResourceManager.GetString("titulo_bairro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Aplicação continua executando na bandeja..
        /// </summary>
        internal static string titulo_ballonText {
            get {
                return ResourceManager.GetString("titulo_ballonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Controle Estoque Zé.
        /// </summary>
        internal static string titulo_ballonTitulo {
            get {
                return ResourceManager.GetString("titulo_ballonTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cargo.
        /// </summary>
        internal static string titulo_cargo {
            get {
                return ResourceManager.GetString("titulo_cargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Categoria.
        /// </summary>
        internal static string titulo_categoria {
            get {
                return ResourceManager.GetString("titulo_categoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cep.
        /// </summary>
        internal static string titulo_cep {
            get {
                return ResourceManager.GetString("titulo_cep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cidade.
        /// </summary>
        internal static string titulo_cidade {
            get {
                return ResourceManager.GetString("titulo_cidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CNPJ.
        /// </summary>
        internal static string titulo_cnpj {
            get {
                return ResourceManager.GetString("titulo_cnpj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Código.
        /// </summary>
        internal static string titulo_codigo {
            get {
                return ResourceManager.GetString("titulo_codigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Complemento.
        /// </summary>
        internal static string titulo_complemento {
            get {
                return ResourceManager.GetString("titulo_complemento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Contato.
        /// </summary>
        internal static string titulo_contato {
            get {
                return ResourceManager.GetString("titulo_contato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CPF.
        /// </summary>
        internal static string titulo_cpf {
            get {
                return ResourceManager.GetString("titulo_cpf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Data Entrada.
        /// </summary>
        internal static string titulo_data {
            get {
                return ResourceManager.GetString("titulo_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Data Nascimento.
        /// </summary>
        internal static string titulo_dataNascimento {
            get {
                return ResourceManager.GetString("titulo_dataNascimento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Descrição.
        /// </summary>
        internal static string titulo_descricao {
            get {
                return ResourceManager.GetString("titulo_descricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Email.
        /// </summary>
        internal static string titulo_email {
            get {
                return ResourceManager.GetString("titulo_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Endereço:.
        /// </summary>
        internal static string titulo_endereco {
            get {
                return ResourceManager.GetString("titulo_endereco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Endereço Fisíco.
        /// </summary>
        internal static string titulo_enderecoFisico {
            get {
                return ResourceManager.GetString("titulo_enderecoFisico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a E&amp;ntradas.
        /// </summary>
        internal static string titulo_entradas {
            get {
                return ResourceManager.GetString("titulo_entradas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &amp;Fornecedor.
        /// </summary>
        internal static string titulo_fornecedor {
            get {
                return ResourceManager.GetString("titulo_fornecedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a F&amp;uncionários.
        /// </summary>
        internal static string titulo_funcionario {
            get {
                return ResourceManager.GetString("titulo_funcionario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Gerente.
        /// </summary>
        internal static string titulo_gerente {
            get {
                return ResourceManager.GetString("titulo_gerente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Grupo.
        /// </summary>
        internal static string titulo_grupo {
            get {
                return ResourceManager.GetString("titulo_grupo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Escolher Idioma.
        /// </summary>
        internal static string titulo_idioma {
            get {
                return ResourceManager.GetString("titulo_idioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ent&amp;rar.
        /// </summary>
        internal static string titulo_logar {
            get {
                return ResourceManager.GetString("titulo_logar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &amp;Loja.
        /// </summary>
        internal static string titulo_loja {
            get {
                return ResourceManager.GetString("titulo_loja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Lote.
        /// </summary>
        internal static string titulo_lote {
            get {
                return ResourceManager.GetString("titulo_lote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Marca.
        /// </summary>
        internal static string titulo_marca {
            get {
                return ResourceManager.GetString("titulo_marca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Matricula.
        /// </summary>
        internal static string titulo_matricula {
            get {
                return ResourceManager.GetString("titulo_matricula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Modelo.
        /// </summary>
        internal static string titulo_modelo {
            get {
                return ResourceManager.GetString("titulo_modelo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nome.
        /// </summary>
        internal static string titulo_nome {
            get {
                return ResourceManager.GetString("titulo_nome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nome Fantasia.
        /// </summary>
        internal static string titulo_nomeFantasia {
            get {
                return ResourceManager.GetString("titulo_nomeFantasia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nota Fiscal.
        /// </summary>
        internal static string titulo_notaFiscal {
            get {
                return ResourceManager.GetString("titulo_notaFiscal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Número.
        /// </summary>
        internal static string titulo_numero {
            get {
                return ResourceManager.GetString("titulo_numero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Pais.
        /// </summary>
        internal static string titulo_pais {
            get {
                return ResourceManager.GetString("titulo_pais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &amp;Produto.
        /// </summary>
        internal static string titulo_produto {
            get {
                return ResourceManager.GetString("titulo_produto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Quantidade.
        /// </summary>
        internal static string titulo_quantidade {
            get {
                return ResourceManager.GetString("titulo_quantidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Rua.
        /// </summary>
        internal static string titulo_rua {
            get {
                return ResourceManager.GetString("titulo_rua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sair.
        /// </summary>
        internal static string titulo_sair {
            get {
                return ResourceManager.GetString("titulo_sair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sexo:.
        /// </summary>
        internal static string titulo_sexo {
            get {
                return ResourceManager.GetString("titulo_sexo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sobre.
        /// </summary>
        internal static string titulo_sobre {
            get {
                return ResourceManager.GetString("titulo_sobre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Razão Social.
        /// </summary>
        internal static string titulo_social {
            get {
                return ResourceManager.GetString("titulo_social", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Status:.
        /// </summary>
        internal static string titulo_status {
            get {
                return ResourceManager.GetString("titulo_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Telefone.
        /// </summary>
        internal static string titulo_telefone {
            get {
                return ResourceManager.GetString("titulo_telefone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tipo:.
        /// </summary>
        internal static string titulo_tipo {
            get {
                return ResourceManager.GetString("titulo_tipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Transportadora.
        /// </summary>
        internal static string titulo_transportadora {
            get {
                return ResourceManager.GetString("titulo_transportadora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Validade.
        /// </summary>
        internal static string titulo_validade {
            get {
                return ResourceManager.GetString("titulo_validade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Valor.
        /// </summary>
        internal static string titulo_valor {
            get {
                return ResourceManager.GetString("titulo_valor", resourceCulture);
            }
        }
    }
}
